<?php

return [
	'dashboard',
	'order',
	'subscription',
	'customer',
	'product',
	'catalog',
	'attribute',
	'coupon',
	'supplier',
	'service',
	'plugin',
	'group',
	'locale' => [
		'locale',
		'locale/site',
		'locale/language',
		'locale/currency',
	],
	'type' => [
		'type/attribute',
		'type/attribute/lists',
		'type/attribute/property',
		'type/catalog/lists',
		'type/customer/lists',
		'type/customer/property',
		'type/media',
		'type/media/lists',
		'type/media/property',
		'type/plugin',
		'type/price',
		'type/price/lists',
		'type/product',
		'type/product/lists',
		'type/product/property',
		'type/service',
		'type/service/lists',
		'type/stock',
		'type/tag',
		'type/text',
		'type/text/lists',
	],
	'log',
];
