<?php

return [
	0 => 'dashboard',
	10 => 'order',
	20 => 'customer',
	30 => 'product',
	40 => 'catalog',
	50 => 'attribute',
	60 => 'coupon',
	70 => 'subscription',
	80 => 'supplier',
	90 => 'service',
	100 => 'plugin',
	110 => 'group',
	120 => [
		'' => 'locale',
		10 => 'locale',
		20 => 'locale/site',
		30 => 'locale/language',
		40 => 'locale/currency',
	],
	130 => [
		'' => 'type',
		10 => 'type/attribute',
		20 => 'type/attribute/lists',
		30 => 'type/attribute/property',
		40 => 'type/catalog/lists',
		50 => 'type/customer/lists',
		60 => 'type/customer/property',
		70 => 'type/media',
		80 => 'type/media/lists',
		90 => 'type/media/property',
		100 => 'type/plugin',
		110 => 'type/price',
		120 => 'type/price/lists',
		130 => 'type/price/property',
		140 => 'type/product',
		150 => 'type/product/lists',
		160 => 'type/product/property',
		170 => 'type/service',
		180 => 'type/service/lists',
		190 => 'type/stock',
		200 => 'type/tag',
		210 => 'type/text',
		220 => 'type/text/lists',
	],
	140 => 'log',
];
